modLoader="javafml"
loaderVersion="[0.15,)"
license="MIT"

[[mods]]
modId="player_automation"
version="1.0.0"
displayName="Player Automation Mod"
description='Automates player actions in a 2-minute loop with keybind toggle.'
authors="You"

[[dependencies.player_automation]]
modId="fabric"
mandatory=true
